export { systemProbe, type SystemProbeRow } from './system.js';

// Phase 2, Task 1 — identity & tenancy data model (ADR 0026).
export {
  tenantStatus,
  userStatus,
  membershipStatus,
  tenants,
  users,
  userTenantMemberships,
  sessions,
  type TenantRow,
  type NewTenantRow,
  type UserRow,
  type NewUserRow,
  type UserTenantMembershipRow,
  type NewUserTenantMembershipRow,
  type SessionRow,
  type NewSessionRow,
} from './identity.js';

export {
  permissions,
  roles,
  rolePermissions,
  membershipRoles,
  type PermissionRow,
  type NewPermissionRow,
  type RoleRow,
  type NewRoleRow,
  type RolePermissionRow,
  type NewRolePermissionRow,
  type MembershipRoleRow,
  type NewMembershipRoleRow,
} from './rbac.js';

// Phase 2, Task 3 — tenant administration & user lifecycle (ADR 0030).
export {
  invitationStatus,
  tenantInvitations,
  outboxEvents,
  type TenantInvitationRow,
  type NewTenantInvitationRow,
  type OutboxEventRow,
  type NewOutboxEventRow,
} from './admin.js';

// Phase 3 — CRM core (ADR 0031).
export {
  leadStatus,
  leadActivityType,
  followupStatus,
  leadOrigin,
  customFieldEntity,
  customFieldDataType,
  customFieldStatus,
  leads,
  leadActivities,
  leadNotes,
  leadFollowups,
  customFieldDefinitions,
  customFieldValues,
  type LeadRow,
  type NewLeadRow,
  type LeadActivityRow,
  type NewLeadActivityRow,
  type LeadNoteRow,
  type NewLeadNoteRow,
  type LeadFollowupRow,
  type NewLeadFollowupRow,
  type CustomFieldDefinitionRow,
  type NewCustomFieldDefinitionRow,
  type CustomFieldValueRow,
  type NewCustomFieldValueRow,
} from './crm.js';

// Phase 3 — inbound integration engine (ADR 0032).
export {
  connectorType,
  sourceStatus,
  rawEventStatus,
  canonicalEventStatus,
  leadSources,
  rawEvents,
  canonicalLeadEvents,
  integrationEventLog,
  type LeadSourceRow,
  type NewLeadSourceRow,
  type RawEventRow,
  type NewRawEventRow,
  type CanonicalLeadEventRow,
  type NewCanonicalLeadEventRow,
  type IntegrationEventLogRow,
  type NewIntegrationEventLogRow,
} from './integrations.js';

// Phase 4 — field operations (ADR 0033).
export {
  fieldAgentStatus,
  visitStatus,
  visitActivityType,
  fieldAgents,
  visits,
  visitActivities,
  visitNotes,
  visitAttachments,
  type FieldAgentRow,
  type NewFieldAgentRow,
  type VisitRow,
  type NewVisitRow,
  type VisitActivityRow,
  type NewVisitActivityRow,
  type VisitNoteRow,
  type NewVisitNoteRow,
  type VisitAttachmentRow,
  type NewVisitAttachmentRow,
} from './field.js';

// Phase 5 — procurement, inventory & logistics (ADR 0034).
export {
  projectStatus,
  projectActivityType,
  warehouseType,
  stockMovementType,
  purchaseOrderStatus,
  dispatchStatus,
  units,
  productCategories,
  products,
  suppliers,
  warehouses,
  projects,
  projectActivities,
  projectMaterials,
  stockLevels,
  stockMovements,
  purchaseOrders,
  purchaseOrderLines,
  goodsReceipts,
  goodsReceiptLines,
  dispatches,
  dispatchLines,
  dispatchAttachments,
  type UnitRow,
  type NewUnitRow,
  type ProductCategoryRow,
  type NewProductCategoryRow,
  type ProductRow,
  type NewProductRow,
  type SupplierRow,
  type NewSupplierRow,
  type WarehouseRow,
  type NewWarehouseRow,
  type ProjectRow,
  type NewProjectRow,
  type ProjectActivityRow,
  type NewProjectActivityRow,
  type ProjectMaterialRow,
  type NewProjectMaterialRow,
  type StockLevelRow,
  type NewStockLevelRow,
  type StockMovementRow,
  type NewStockMovementRow,
  type PurchaseOrderRow,
  type NewPurchaseOrderRow,
  type PurchaseOrderLineRow,
  type NewPurchaseOrderLineRow,
  type GoodsReceiptRow,
  type NewGoodsReceiptRow,
  type GoodsReceiptLineRow,
  type NewGoodsReceiptLineRow,
  type DispatchRow,
  type NewDispatchRow,
  type DispatchLineRow,
  type NewDispatchLineRow,
  type DispatchAttachmentRow,
  type NewDispatchAttachmentRow,
} from './supply.js';

// Phase 6 — commercial: customers, quotations & project booking (ADR 0035).
export {
  customerStatus,
  quotationStatus,
  quotationRevisionStatus,
  quotationActivityType,
  customers,
  quotations,
  quotationRevisions,
  quotationLines,
  quotationActivities,
  quotationAttachments,
  type CustomerRow,
  type NewCustomerRow,
  type QuotationRow,
  type NewQuotationRow,
  type QuotationRevisionRow,
  type NewQuotationRevisionRow,
  type QuotationLineRow,
  type NewQuotationLineRow,
  type QuotationActivityRow,
  type NewQuotationActivityRow,
  type QuotationAttachmentRow,
  type NewQuotationAttachmentRow,
} from './commercial.js';

// Phase 7 — EPC project execution (ADR 0036).
export {
  projectMilestoneKey,
  projectMilestoneStatus,
  installationStatus,
  checklistKind,
  checklistItemStatus,
  qcInspectionStatus,
  defectSeverity,
  defectStatus,
  netMeteringStatus,
  handoverStatus,
  executionAttachmentEntity,
  projectMilestones,
  projectInstallations,
  checklistTemplates,
  projectChecklistItems,
  projectQcInspections,
  projectDefects,
  projectNetMetering,
  projectHandover,
  projectExecutionAttachments,
  type ProjectMilestoneRow,
  type NewProjectMilestoneRow,
  type ProjectInstallationRow,
  type NewProjectInstallationRow,
  type ChecklistTemplateRow,
  type NewChecklistTemplateRow,
  type ProjectChecklistItemRow,
  type NewProjectChecklistItemRow,
  type ProjectQcInspectionRow,
  type NewProjectQcInspectionRow,
  type ProjectDefectRow,
  type NewProjectDefectRow,
  type ProjectNetMeteringRow,
  type NewProjectNetMeteringRow,
  type ProjectHandoverRow,
  type NewProjectHandoverRow,
  type ProjectExecutionAttachmentRow,
  type NewProjectExecutionAttachmentRow,
} from './execution.js';

// Phase 8 — Notifications & Communications Engine (ADR 0037).
export {
  notificationChannel,
  notificationType,
  notificationDeliveryStatus,
  notificationRecipientStrategy,
  notificationTemplates,
  notificationRules,
  notificationPreferences,
  notifications,
  notificationDeliveries,
  type NotificationTemplateRow,
  type NewNotificationTemplateRow,
  type NotificationRuleRow,
  type NewNotificationRuleRow,
  type NotificationPreferenceRow,
  type NewNotificationPreferenceRow,
  type NotificationRow,
  type NewNotificationRow,
  type NotificationDeliveryRow,
  type NewNotificationDeliveryRow,
} from './notifications.js';

// Phase 9 — Finance: operational invoicing & payments (ADR 0038).
export {
  invoiceStatus,
  lineDiscountType,
  paymentStatus,
  paymentMethod,
  creditNoteStatus,
  invoiceSource,
  financeCounters,
  financeIdempotency,
  invoices,
  invoiceLines,
  payments,
  paymentAllocations,
  creditNotes,
  type FinanceCounterRow,
  type NewFinanceCounterRow,
  type FinanceIdempotencyRow,
  type NewFinanceIdempotencyRow,
  type InvoiceRow,
  type NewInvoiceRow,
  type InvoiceLineRow,
  type NewInvoiceLineRow,
  type PaymentRow,
  type NewPaymentRow,
  type PaymentAllocationRow,
  type NewPaymentAllocationRow,
  type CreditNoteRow,
  type NewCreditNoteRow,
} from './finance.js';

// Phase 10 — Tenant company profile, branding & onboarding (ADR 0039).
export {
  tenantAssetKind,
  tenantCompanyProfiles,
  tenantAssets,
  tenantOnboarding,
  type TenantCompanyProfileRow,
  type NewTenantCompanyProfileRow,
  type TenantAssetRow,
  type NewTenantAssetRow,
  type TenantOnboardingRow,
  type NewTenantOnboardingRow,
} from './branding.js';

// Phase 11 — Global Audit Log (ADR 0040).
export {
  auditActorType,
  auditModule,
  auditLogs,
  type AuditLogRow,
  type NewAuditLogRow,
} from './audit.js';

export {
  usersRelations,
  tenantsRelations,
  sessionsRelations,
  userTenantMembershipsRelations,
  rolesRelations,
  permissionsRelations,
  rolePermissionsRelations,
  membershipRolesRelations,
  tenantInvitationsRelations,
  outboxEventsRelations,
  leadsRelations,
  leadActivitiesRelations,
  leadNotesRelations,
  leadFollowupsRelations,
  customFieldDefinitionsRelations,
  customFieldValuesRelations,
  leadSourcesRelations,
  rawEventsRelations,
  canonicalLeadEventsRelations,
  integrationEventLogRelations,
  fieldAgentsRelations,
  visitsRelations,
  visitActivitiesRelations,
  visitNotesRelations,
  visitAttachmentsRelations,
  productsRelations,
  suppliersRelations,
  warehousesRelations,
  projectsRelations,
  projectMaterialsRelations,
  projectActivitiesRelations,
  stockLevelsRelations,
  stockMovementsRelations,
  purchaseOrdersRelations,
  purchaseOrderLinesRelations,
  goodsReceiptsRelations,
  goodsReceiptLinesRelations,
  dispatchesRelations,
  dispatchLinesRelations,
  dispatchAttachmentsRelations,
  customersRelations,
  quotationsRelations,
  quotationRevisionsRelations,
  quotationLinesRelations,
  quotationActivitiesRelations,
  quotationAttachmentsRelations,
  projectMilestonesRelations,
  projectInstallationsRelations,
  projectChecklistItemsRelations,
  projectQcInspectionsRelations,
  projectDefectsRelations,
  projectNetMeteringRelations,
  projectHandoverRelations,
  projectExecutionAttachmentsRelations,
  notificationTemplatesRelations,
  notificationRulesRelations,
  notificationPreferencesRelations,
  notificationsRelations,
  notificationDeliveriesRelations,
  invoicesRelations,
  invoiceLinesRelations,
  paymentsRelations,
  paymentAllocationsRelations,
  creditNotesRelations,
  tenantCompanyProfilesRelations,
  tenantAssetsRelations,
  tenantOnboardingRelations,
  auditLogsRelations,
} from './relations.js';
