export { systemProbe, type SystemProbeRow } from './system.js';

// Phase 2, Task 1 — identity & tenancy data model (ADR 0026).
export {
  tenantStatus,
  userStatus,
  membershipStatus,
  tenants,
  users,
  userTenantMemberships,
  sessions,
  type TenantRow,
  type NewTenantRow,
  type UserRow,
  type NewUserRow,
  type UserTenantMembershipRow,
  type NewUserTenantMembershipRow,
  type SessionRow,
  type NewSessionRow,
} from './identity.js';

export {
  permissions,
  roles,
  rolePermissions,
  membershipRoles,
  roleKind,
  dataScope,
  type PermissionRow,
  type NewPermissionRow,
  type RoleRow,
  type NewRoleRow,
  type RolePermissionRow,
  type NewRolePermissionRow,
  type MembershipRoleRow,
  type NewMembershipRoleRow,
  type RoleKind,
  type DataScope,
} from './rbac.js';

// Phase 13 — Platform access & module entitlements (ADR 0042).
export {
  platformAdmins,
  moduleEntitlementState,
  tenantModuleEntitlements,
  type PlatformAdminRow,
  type NewPlatformAdminRow,
  type TenantModuleEntitlementRow,
  type NewTenantModuleEntitlementRow,
} from './platform.js';

// Phase 2, Task 3 — tenant administration & user lifecycle (ADR 0030).
export {
  invitationStatus,
  tenantInvitations,
  outboxEvents,
  type TenantInvitationRow,
  type NewTenantInvitationRow,
  type OutboxEventRow,
  type NewOutboxEventRow,
} from './admin.js';

// Phase 3 — CRM core (ADR 0031).
export {
  leadStatus,
  leadActivityType,
  followupStatus,
  leadOrigin,
  customFieldEntity,
  customFieldDataType,
  customFieldStatus,
  leads,
  leadActivities,
  leadNotes,
  leadFollowups,
  customFieldDefinitions,
  customFieldValues,
  type LeadRow,
  type NewLeadRow,
  type LeadActivityRow,
  type NewLeadActivityRow,
  type LeadNoteRow,
  type NewLeadNoteRow,
  type LeadFollowupRow,
  type NewLeadFollowupRow,
  type CustomFieldDefinitionRow,
  type NewCustomFieldDefinitionRow,
  type CustomFieldValueRow,
  type NewCustomFieldValueRow,
} from './crm.js';

// Phase 3 — inbound integration engine (ADR 0032).
export {
  connectorType,
  sourceStatus,
  rawEventStatus,
  canonicalEventStatus,
  leadSources,
  rawEvents,
  canonicalLeadEvents,
  integrationEventLog,
  type LeadSourceRow,
  type NewLeadSourceRow,
  type RawEventRow,
  type NewRawEventRow,
  type CanonicalLeadEventRow,
  type NewCanonicalLeadEventRow,
  type IntegrationEventLogRow,
  type NewIntegrationEventLogRow,
} from './integrations.js';

// Phase 4 — field operations (ADR 0033).
export {
  fieldAgentStatus,
  visitStatus,
  visitActivityType,
  fieldAgents,
  visits,
  visitActivities,
  visitNotes,
  visitAttachments,
  type FieldAgentRow,
  type NewFieldAgentRow,
  type VisitRow,
  type NewVisitRow,
  type VisitActivityRow,
  type NewVisitActivityRow,
  type VisitNoteRow,
  type NewVisitNoteRow,
  type VisitAttachmentRow,
  type NewVisitAttachmentRow,
} from './field.js';

// Phase 5 — procurement, inventory & logistics (ADR 0034).
export {
  projectStatus,
  projectActivityType,
  warehouseType,
  stockMovementType,
  purchaseOrderStatus,
  dispatchStatus,
  units,
  productCategories,
  products,
  suppliers,
  warehouses,
  projects,
  projectActivities,
  projectMaterials,
  stockLevels,
  stockMovements,
  purchaseOrders,
  purchaseOrderLines,
  goodsReceipts,
  goodsReceiptLines,
  dispatches,
  dispatchLines,
  dispatchAttachments,
  type UnitRow,
  type NewUnitRow,
  type ProductCategoryRow,
  type NewProductCategoryRow,
  type ProductRow,
  type NewProductRow,
  type SupplierRow,
  type NewSupplierRow,
  type WarehouseRow,
  type NewWarehouseRow,
  type ProjectRow,
  type NewProjectRow,
  type ProjectActivityRow,
  type NewProjectActivityRow,
  type ProjectMaterialRow,
  type NewProjectMaterialRow,
  type StockLevelRow,
  type NewStockLevelRow,
  type StockMovementRow,
  type NewStockMovementRow,
  type PurchaseOrderRow,
  type NewPurchaseOrderRow,
  type PurchaseOrderLineRow,
  type NewPurchaseOrderLineRow,
  type GoodsReceiptRow,
  type NewGoodsReceiptRow,
  type GoodsReceiptLineRow,
  type NewGoodsReceiptLineRow,
  type DispatchRow,
  type NewDispatchRow,
  type DispatchLineRow,
  type NewDispatchLineRow,
  type DispatchAttachmentRow,
  type NewDispatchAttachmentRow,
} from './supply.js';

// Phase 6 — commercial: customers, quotations & project booking (ADR 0035).
export {
  customerStatus,
  quotationStatus,
  quotationRevisionStatus,
  quotationActivityType,
  customers,
  quotations,
  quotationRevisions,
  quotationLines,
  quotationActivities,
  quotationAttachments,
  type CustomerRow,
  type NewCustomerRow,
  type QuotationRow,
  type NewQuotationRow,
  type QuotationRevisionRow,
  type NewQuotationRevisionRow,
  type QuotationLineRow,
  type NewQuotationLineRow,
  type QuotationActivityRow,
  type NewQuotationActivityRow,
  type QuotationAttachmentRow,
  type NewQuotationAttachmentRow,
} from './commercial.js';

// Phase 7 — EPC project execution (ADR 0036).
export {
  projectMilestoneKey,
  projectMilestoneStatus,
  installationStatus,
  checklistKind,
  checklistItemStatus,
  qcInspectionStatus,
  defectSeverity,
  defectStatus,
  netMeteringStatus,
  handoverStatus,
  executionAttachmentEntity,
  projectMilestones,
  projectInstallations,
  checklistTemplates,
  projectChecklistItems,
  projectQcInspections,
  projectDefects,
  projectNetMetering,
  projectHandover,
  projectExecutionAttachments,
  type ProjectMilestoneRow,
  type NewProjectMilestoneRow,
  type ProjectInstallationRow,
  type NewProjectInstallationRow,
  type ChecklistTemplateRow,
  type NewChecklistTemplateRow,
  type ProjectChecklistItemRow,
  type NewProjectChecklistItemRow,
  type ProjectQcInspectionRow,
  type NewProjectQcInspectionRow,
  type ProjectDefectRow,
  type NewProjectDefectRow,
  type ProjectNetMeteringRow,
  type NewProjectNetMeteringRow,
  type ProjectHandoverRow,
  type NewProjectHandoverRow,
  type ProjectExecutionAttachmentRow,
  type NewProjectExecutionAttachmentRow,
} from './execution.js';

// Phase 8 — Notifications & Communications Engine (ADR 0037).
export {
  notificationChannel,
  notificationType,
  notificationDeliveryStatus,
  notificationRecipientStrategy,
  notificationTemplates,
  notificationRules,
  notificationPreferences,
  notifications,
  notificationDeliveries,
  type NotificationTemplateRow,
  type NewNotificationTemplateRow,
  type NotificationRuleRow,
  type NewNotificationRuleRow,
  type NotificationPreferenceRow,
  type NewNotificationPreferenceRow,
  type NotificationRow,
  type NewNotificationRow,
  type NotificationDeliveryRow,
  type NewNotificationDeliveryRow,
} from './notifications.js';

// Phase 9 — Finance: operational invoicing & payments (ADR 0038).
export {
  invoiceStatus,
  lineDiscountType,
  paymentStatus,
  paymentMethod,
  creditNoteStatus,
  invoiceSource,
  financeCounters,
  financeIdempotency,
  invoices,
  invoiceLines,
  payments,
  paymentAllocations,
  creditNotes,
  type FinanceCounterRow,
  type NewFinanceCounterRow,
  type FinanceIdempotencyRow,
  type NewFinanceIdempotencyRow,
  type InvoiceRow,
  type NewInvoiceRow,
  type InvoiceLineRow,
  type NewInvoiceLineRow,
  type PaymentRow,
  type NewPaymentRow,
  type PaymentAllocationRow,
  type NewPaymentAllocationRow,
  type CreditNoteRow,
  type NewCreditNoteRow,
} from './finance.js';

// Phase 10 — Tenant company profile, branding & onboarding (ADR 0039).
export {
  tenantAssetKind,
  tenantCompanyProfiles,
  tenantAssets,
  tenantOnboarding,
  type TenantCompanyProfileRow,
  type NewTenantCompanyProfileRow,
  type TenantAssetRow,
  type NewTenantAssetRow,
  type TenantOnboardingRow,
  type NewTenantOnboardingRow,
} from './branding.js';

// Phase 11 — Global Audit Log (ADR 0040).
export {
  auditActorType,
  auditModule,
  auditLogs,
  type AuditLogRow,
  type NewAuditLogRow,
} from './audit.js';

// Phase 12 — HR & Workforce Management (ADR 0041).
export {
  employeeStatus,
  employmentType,
  orgUnitStatus,
  employmentChangeType,
  attendanceStatus,
  attendanceSource,
  halfDayPeriod,
  leaveApproverStrategy,
  leaveRequestStatus,
  leaveBalanceTxnKind,
  expenseClaimStatus,
  reimbursementStatus,
  hrPaymentMethod,
  payFrequency,
  compensationStatus,
  salaryComponentKind,
  payrollPeriodStatus,
  payrollPaymentStatus,
  incentiveStatus,
  performancePeriodStatus,
  performanceGoalStatus,
  performanceReviewStatus,
  hrCounters,
  departments,
  designations,
  workLocations,
  workSchedules,
  employees,
  employmentHistory,
  employeeBankDetails,
  employeeDocuments,
  attendanceRecords,
  attendanceCorrections,
  leaveTypes,
  leavePolicies,
  leaveBalances,
  leaveRequests,
  leaveBalanceTransactions,
  expenseCategories,
  expenseClaims,
  expenseReimbursements,
  compensationProfiles,
  compensationComponents,
  incentives,
  payrollPeriods,
  payrollEntries,
  payrollEntryComponents,
  payrollPayments,
  performancePeriods,
  performanceGoals,
  performanceReviews,
  type HrCounterRow,
  type DepartmentRow,
  type NewDepartmentRow,
  type DesignationRow,
  type NewDesignationRow,
  type WorkLocationRow,
  type NewWorkLocationRow,
  type WorkScheduleRow,
  type NewWorkScheduleRow,
  type EmployeeRow,
  type NewEmployeeRow,
  type EmploymentHistoryRow,
  type NewEmploymentHistoryRow,
  type EmployeeBankDetailsRow,
  type NewEmployeeBankDetailsRow,
  type EmployeeDocumentRow,
  type NewEmployeeDocumentRow,
  type AttendanceRecordRow,
  type NewAttendanceRecordRow,
  type AttendanceCorrectionRow,
  type NewAttendanceCorrectionRow,
  type LeaveTypeRow,
  type NewLeaveTypeRow,
  type LeavePolicyRow,
  type NewLeavePolicyRow,
  type LeaveBalanceRow,
  type NewLeaveBalanceRow,
  type LeaveRequestRow,
  type NewLeaveRequestRow,
  type LeaveBalanceTransactionRow,
  type NewLeaveBalanceTransactionRow,
  type ExpenseCategoryRow,
  type NewExpenseCategoryRow,
  type ExpenseClaimRow,
  type NewExpenseClaimRow,
  type ExpenseReimbursementRow,
  type NewExpenseReimbursementRow,
  type CompensationProfileRow,
  type NewCompensationProfileRow,
  type CompensationComponentRow,
  type NewCompensationComponentRow,
  type IncentiveRow,
  type NewIncentiveRow,
  type PayrollPeriodRow,
  type NewPayrollPeriodRow,
  type PayrollEntryRow,
  type NewPayrollEntryRow,
  type PayrollEntryComponentRow,
  type NewPayrollEntryComponentRow,
  type PayrollPaymentRow,
  type NewPayrollPaymentRow,
  type PerformancePeriodRow,
  type NewPerformancePeriodRow,
  type PerformanceGoalRow,
  type NewPerformanceGoalRow,
  type PerformanceReviewRow,
  type NewPerformanceReviewRow,
} from './hr.js';

export {
  usersRelations,
  tenantsRelations,
  sessionsRelations,
  userTenantMembershipsRelations,
  rolesRelations,
  permissionsRelations,
  rolePermissionsRelations,
  membershipRolesRelations,
  tenantInvitationsRelations,
  outboxEventsRelations,
  leadsRelations,
  leadActivitiesRelations,
  leadNotesRelations,
  leadFollowupsRelations,
  customFieldDefinitionsRelations,
  customFieldValuesRelations,
  leadSourcesRelations,
  rawEventsRelations,
  canonicalLeadEventsRelations,
  integrationEventLogRelations,
  fieldAgentsRelations,
  visitsRelations,
  visitActivitiesRelations,
  visitNotesRelations,
  visitAttachmentsRelations,
  productsRelations,
  suppliersRelations,
  warehousesRelations,
  projectsRelations,
  projectMaterialsRelations,
  projectActivitiesRelations,
  stockLevelsRelations,
  stockMovementsRelations,
  purchaseOrdersRelations,
  purchaseOrderLinesRelations,
  goodsReceiptsRelations,
  goodsReceiptLinesRelations,
  dispatchesRelations,
  dispatchLinesRelations,
  dispatchAttachmentsRelations,
  customersRelations,
  quotationsRelations,
  quotationRevisionsRelations,
  quotationLinesRelations,
  quotationActivitiesRelations,
  quotationAttachmentsRelations,
  projectMilestonesRelations,
  projectInstallationsRelations,
  projectChecklistItemsRelations,
  projectQcInspectionsRelations,
  projectDefectsRelations,
  projectNetMeteringRelations,
  projectHandoverRelations,
  projectExecutionAttachmentsRelations,
  notificationTemplatesRelations,
  notificationRulesRelations,
  notificationPreferencesRelations,
  notificationsRelations,
  notificationDeliveriesRelations,
  invoicesRelations,
  invoiceLinesRelations,
  paymentsRelations,
  paymentAllocationsRelations,
  creditNotesRelations,
  tenantCompanyProfilesRelations,
  tenantAssetsRelations,
  tenantOnboardingRelations,
  auditLogsRelations,
} from './relations.js';
